//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DspCallCG.GetPaymentToken {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ESBGatewaySoap2", Namespace="http://www.fnx.co.il")]
    public partial class GetPaymentToken_ESBGW : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPaymentToken_ReqResSvcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPaymentToken_ESBGW() {
            this.Url = "http://172.31.196.20:80/ESBGatewayExperanto/Services/GetPaymentToken.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPaymentToken_ReqResSvcCompletedEventHandler GetPaymentToken_ReqResSvcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fnx.co.il/GenericGateway/RequestResponseService", RequestNamespace="http://www.fnx.co.il", ResponseNamespace="http://www.fnx.co.il", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PaymentToken", Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
        public PaymentToken1 GetPaymentToken_ReqResSvc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenRequest")] PaymentToken PaymentToken, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas", IsNullable=true)] ESBServiceRequestMetadata ESBServiceRequestMetadata, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fnx.co.il/ESB")] out ESBServiceResponseMetadata ESBServiceResponseMetadata) {
            object[] results = this.Invoke("GetPaymentToken_ReqResSvc", new object[] {
                        PaymentToken,
                        ESBServiceRequestMetadata});
            ESBServiceResponseMetadata = ((ESBServiceResponseMetadata)(results[1]));
            return ((PaymentToken1)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentToken_ReqResSvcAsync(PaymentToken PaymentToken, ESBServiceRequestMetadata ESBServiceRequestMetadata) {
            this.GetPaymentToken_ReqResSvcAsync(PaymentToken, ESBServiceRequestMetadata, null);
        }
        
        /// <remarks/>
        public void GetPaymentToken_ReqResSvcAsync(PaymentToken PaymentToken, ESBServiceRequestMetadata ESBServiceRequestMetadata, object userState) {
            if ((this.GetPaymentToken_ReqResSvcOperationCompleted == null)) {
                this.GetPaymentToken_ReqResSvcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentToken_ReqResSvcOperationCompleted);
            }
            this.InvokeAsync("GetPaymentToken_ReqResSvc", new object[] {
                        PaymentToken,
                        ESBServiceRequestMetadata}, this.GetPaymentToken_ReqResSvcOperationCompleted, userState);
        }
        
        private void OnGetPaymentToken_ReqResSvcOperationCompleted(object arg) {
            if ((this.GetPaymentToken_ReqResSvcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentToken_ReqResSvcCompleted(this, new GetPaymentToken_ReqResSvcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenRequest")]
    public partial class PaymentToken {
        
        private PaymentTokenRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenRequest")]
    public partial class PaymentTokenRequest {
        
        private string mpiTransactionIdField;
        
        private string midField;
        
        private string terminalNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpiTransactionId {
            get {
                return this.mpiTransactionIdField;
            }
            set {
                this.mpiTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mid {
            get {
                return this.midField;
            }
            set {
                this.midField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalNumber {
            get {
                return this.terminalNumberField;
            }
            set {
                this.terminalNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/ESB")]
    public partial class ESBServiceResponseMetadata {
        
        private ResponseStatus responseStatusField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string responseCodeOriginatorField;
        
        private string serviceInstanceIdField;
        
        private long instanceWFIDField;
        
        private string correlationIdField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeOriginator {
            get {
                return this.responseCodeOriginatorField;
            }
            set {
                this.responseCodeOriginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInstanceId {
            get {
                return this.serviceInstanceIdField;
            }
            set {
                this.serviceInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public long InstanceWFID {
            get {
                return this.instanceWFIDField;
            }
            set {
                this.instanceWFIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/ESB")]
    public enum ResponseStatus {
        
        /// <remarks/>
        NotDefined,
        
        /// <remarks/>
        AsyncPending,
        
        /// <remarks/>
        DecisionPending,
        
        /// <remarks/>
        NotApplicable,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        NoDataFound,
        
        /// <remarks/>
        BusinessError,
        
        /// <remarks/>
        TechnicalError,
        
        /// <remarks/>
        Canceled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Process {
        
        private string processCodeField;
        
        private Id idField;
        
        /// <remarks/>
        public string ProcessCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        public Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Id {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Filter {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class ESBServiceRequestMetadata {
        
        private Filter filterField;
        
        private Id idField;
        
        private Process processField;
        
        private string callingAppInstanceTrackingIdField;
        
        private string versionField;
        
        private string interfaceField;
        
        private string callerField;
        
        private System.DateTime activityTimeField;
        
        private bool activityTimeFieldSpecified;
        
        private string serviceInstanceIdField;
        
        private string workspaceField;
        
        private string correlationIdField;
        
        /// <remarks/>
        public Filter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Process Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        public string CallingAppInstanceTrackingId {
            get {
                return this.callingAppInstanceTrackingIdField;
            }
            set {
                this.callingAppInstanceTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Interface {
            get {
                return this.interfaceField;
            }
            set {
                this.interfaceField = value;
            }
        }
        
        /// <remarks/>
        public string Caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActivityTime {
            get {
                return this.activityTimeField;
            }
            set {
                this.activityTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivityTimeSpecified {
            get {
                return this.activityTimeFieldSpecified;
            }
            set {
                this.activityTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInstanceId {
            get {
                return this.serviceInstanceIdField;
            }
            set {
                this.serviceInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public string Workspace {
            get {
                return this.workspaceField;
            }
            set {
                this.workspaceField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentToken1 {
        
        private PaymentTokenResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponse response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponse {
        
        private string commandField;
        
        private string dateTimeField;
        
        private string requestIdField;
        
        private string tranIdField;
        
        private string resultField;
        
        private string messageField;
        
        private string userMessageField;
        
        private string additionalInfoField;
        
        private string versionField;
        
        private string languageField;
        
        private PaymentTokenResponseInquireTransactions inquireTransactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tranId {
            get {
                return this.tranIdField;
            }
            set {
                this.tranIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userMessage {
            get {
                return this.userMessageField;
            }
            set {
                this.userMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactions inquireTransactions {
            get {
                return this.inquireTransactionsField;
            }
            set {
                this.inquireTransactionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactions {
        
        private PaymentTokenResponseInquireTransactionsRow rowField;
        
        private PaymentTokenResponseInquireTransactionsTotals totalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRow row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsTotals totals {
            get {
                return this.totalsField;
            }
            set {
                this.totalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRow {
        
        private string mpiTransactionIdField;
        
        private string uniqueidField;
        
        private string amountField;
        
        private string currencyField;
        
        private string authNumberField;
        
        private string cardIdField;
        
        private string languageCodeField;
        
        private string statusCodeField;
        
        private string statusTextField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        private string cgGatewayResponseCodeField;
        
        private string cgGatewayResponseTextField;
        
        private PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXML cgGatewayResponseXMLField;
        
        private string queryErrorTextField;
        
        private string xRemField;
        
        private string costumerIdField;
        
        private string cardExpirationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpiTransactionId {
            get {
                return this.mpiTransactionIdField;
            }
            set {
                this.mpiTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uniqueid {
            get {
                return this.uniqueidField;
            }
            set {
                this.uniqueidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authNumber {
            get {
                return this.authNumberField;
            }
            set {
                this.authNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgGatewayResponseCode {
            get {
                return this.cgGatewayResponseCodeField;
            }
            set {
                this.cgGatewayResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgGatewayResponseText {
            get {
                return this.cgGatewayResponseTextField;
            }
            set {
                this.cgGatewayResponseTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXML cgGatewayResponseXML {
            get {
                return this.cgGatewayResponseXMLField;
            }
            set {
                this.cgGatewayResponseXMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryErrorText {
            get {
                return this.queryErrorTextField;
            }
            set {
                this.queryErrorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xRem {
            get {
                return this.xRemField;
            }
            set {
                this.xRemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string costumerId {
            get {
                return this.costumerIdField;
            }
            set {
                this.costumerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardExpiration {
            get {
                return this.cardExpirationField;
            }
            set {
                this.cardExpirationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXML {
        
        private PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshrait ashraitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshrait ashrait {
            get {
                return this.ashraitField;
            }
            set {
                this.ashraitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshrait {
        
        private PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponse response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponse {
        
        private string commandField;
        
        private string dateTimeField;
        
        private string requestIdField;
        
        private string tranIdField;
        
        private string resultField;
        
        private string messageField;
        
        private string userMessageField;
        
        private string additionalInfoField;
        
        private string versionField;
        
        private string languageField;
        
        private PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDeal doDealField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tranId {
            get {
                return this.tranIdField;
            }
            set {
                this.tranIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userMessage {
            get {
                return this.userMessageField;
            }
            set {
                this.userMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDeal doDeal {
            get {
                return this.doDealField;
            }
            set {
                this.doDealField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDeal {
        
        private string statusField;
        
        private string statusTextField;
        
        private string terminalNumberField;
        
        private string cardIdField;
        
        private string cardBinField;
        
        private string cardMaskField;
        
        private string cardLengthField;
        
        private string cardNoField;
        
        private string cardNameField;
        
        private string cardExpirationField;
        
        private string cardTypeField;
        
        private string extendedCardTypeField;
        
        private string creditCompanyField;
        
        private string creditCompanyCodeField;
        
        private string cardBrandField;
        
        private string cardBrandCodeField;
        
        private string cardAcquirerField;
        
        private string cardAcquirerCodeField;
        
        private string serviceCodeField;
        
        private string transactionTypeField;
        
        private string creditTypeField;
        
        private string currencyField;
        
        private string transactionCodeField;
        
        private string totalField;
        
        private string balanceField;
        
        private string starTotalField;
        
        private string firstPaymentField;
        
        private string periodicalPaymentField;
        
        private string numberOfPaymentsField;
        
        private string clubIdField;
        
        private string clubCodeField;
        
        private string validationField;
        
        private string commReasonField;
        
        private string idStatusField;
        
        private string cvvStatusField;
        
        private string authSourceField;
        
        private string authNumberField;
        
        private string fileNumberField;
        
        private string slaveTerminalNumberField;
        
        private string slaveTerminalSequenceField;
        
        private string creditGroupField;
        
        private string pinKeyInField;
        
        private string pfscField;
        
        private string eciField;
        
        private string cavvField;
        
        private string userField;
        
        private string addonDataField;
        
        private string supplierNumberField;
        
        private PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDealCustomerData customerDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalNumber {
            get {
                return this.terminalNumberField;
            }
            set {
                this.terminalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardBin {
            get {
                return this.cardBinField;
            }
            set {
                this.cardBinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardMask {
            get {
                return this.cardMaskField;
            }
            set {
                this.cardMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardLength {
            get {
                return this.cardLengthField;
            }
            set {
                this.cardLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardExpiration {
            get {
                return this.cardExpirationField;
            }
            set {
                this.cardExpirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedCardType {
            get {
                return this.extendedCardTypeField;
            }
            set {
                this.extendedCardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditCompany {
            get {
                return this.creditCompanyField;
            }
            set {
                this.creditCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditCompanyCode {
            get {
                return this.creditCompanyCodeField;
            }
            set {
                this.creditCompanyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardBrand {
            get {
                return this.cardBrandField;
            }
            set {
                this.cardBrandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardBrandCode {
            get {
                return this.cardBrandCodeField;
            }
            set {
                this.cardBrandCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardAcquirer {
            get {
                return this.cardAcquirerField;
            }
            set {
                this.cardAcquirerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardAcquirerCode {
            get {
                return this.cardAcquirerCodeField;
            }
            set {
                this.cardAcquirerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditType {
            get {
                return this.creditTypeField;
            }
            set {
                this.creditTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string starTotal {
            get {
                return this.starTotalField;
            }
            set {
                this.starTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstPayment {
            get {
                return this.firstPaymentField;
            }
            set {
                this.firstPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodicalPayment {
            get {
                return this.periodicalPaymentField;
            }
            set {
                this.periodicalPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numberOfPayments {
            get {
                return this.numberOfPaymentsField;
            }
            set {
                this.numberOfPaymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clubId {
            get {
                return this.clubIdField;
            }
            set {
                this.clubIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clubCode {
            get {
                return this.clubCodeField;
            }
            set {
                this.clubCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validation {
            get {
                return this.validationField;
            }
            set {
                this.validationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commReason {
            get {
                return this.commReasonField;
            }
            set {
                this.commReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cvvStatus {
            get {
                return this.cvvStatusField;
            }
            set {
                this.cvvStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authSource {
            get {
                return this.authSourceField;
            }
            set {
                this.authSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authNumber {
            get {
                return this.authNumberField;
            }
            set {
                this.authNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string slaveTerminalNumber {
            get {
                return this.slaveTerminalNumberField;
            }
            set {
                this.slaveTerminalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string slaveTerminalSequence {
            get {
                return this.slaveTerminalSequenceField;
            }
            set {
                this.slaveTerminalSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditGroup {
            get {
                return this.creditGroupField;
            }
            set {
                this.creditGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pinKeyIn {
            get {
                return this.pinKeyInField;
            }
            set {
                this.pinKeyInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pfsc {
            get {
                return this.pfscField;
            }
            set {
                this.pfscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eci {
            get {
                return this.eciField;
            }
            set {
                this.eciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cavv {
            get {
                return this.cavvField;
            }
            set {
                this.cavvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addonData {
            get {
                return this.addonDataField;
            }
            set {
                this.addonDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplierNumber {
            get {
                return this.supplierNumberField;
            }
            set {
                this.supplierNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDealCustomerData customerData {
            get {
                return this.customerDataField;
            }
            set {
                this.customerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsRowCgGatewayResponseXMLAshraitResponseDoDealCustomerData {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.GetPaymentTokenResponse")]
    public partial class PaymentTokenResponseInquireTransactionsTotals {
        
        private string pageNumberField;
        
        private string pagesAmountField;
        
        private string queryResultIdField;
        
        private string totalField;
        
        private string totalMatchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pagesAmount {
            get {
                return this.pagesAmountField;
            }
            set {
                this.pagesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryResultId {
            get {
                return this.queryResultIdField;
            }
            set {
                this.queryResultIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string totalMatch {
            get {
                return this.totalMatchField;
            }
            set {
                this.totalMatchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPaymentToken_ReqResSvcCompletedEventHandler(object sender, GetPaymentToken_ReqResSvcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentToken_ReqResSvcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentToken_ReqResSvcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentToken1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentToken1)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ESBServiceResponseMetadata ESBServiceResponseMetadata {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ESBServiceResponseMetadata)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591