//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DspCallCG.GetPaymentURL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ESBGatewaySoap2", Namespace="http://www.fnx.co.il")]
    public partial class GetPaymentURL_ESBGW : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPaymentURL_ReqResSvcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPaymentURL_ESBGW() {
            this.Url = global::DspCallCG.Properties.Settings.Default.DspCallCG_GetPaymentURL_ESBGateway;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPaymentURL_ReqResSvcCompletedEventHandler GetPaymentURL_ReqResSvcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fnx.co.il/GenericGateway/RequestResponseService", RequestNamespace="http://www.fnx.co.il", ResponseNamespace="http://www.fnx.co.il", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ashrait", Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdResponseURL")]
        public ashrait1 GetPaymentURL_ReqResSvc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdRequestURL")] ashrait ashrait, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas", IsNullable=true)] ESBServiceRequestMetadata ESBServiceRequestMetadata, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fnx.co.il/ESB")] out ESBServiceResponseMetadata ESBServiceResponseMetadata) {
            object[] results = this.Invoke("GetPaymentURL_ReqResSvc", new object[] {
                        ashrait,
                        ESBServiceRequestMetadata});
            ESBServiceResponseMetadata = ((ESBServiceResponseMetadata)(results[1]));
            return ((ashrait1)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentURL_ReqResSvcAsync(ashrait ashrait, ESBServiceRequestMetadata ESBServiceRequestMetadata) {
            this.GetPaymentURL_ReqResSvcAsync(ashrait, ESBServiceRequestMetadata, null);
        }
        
        /// <remarks/>
        public void GetPaymentURL_ReqResSvcAsync(ashrait ashrait, ESBServiceRequestMetadata ESBServiceRequestMetadata, object userState) {
            if ((this.GetPaymentURL_ReqResSvcOperationCompleted == null)) {
                this.GetPaymentURL_ReqResSvcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentURL_ReqResSvcOperationCompleted);
            }
            this.InvokeAsync("GetPaymentURL_ReqResSvc", new object[] {
                        ashrait,
                        ESBServiceRequestMetadata}, this.GetPaymentURL_ReqResSvcOperationCompleted, userState);
        }
        
        private void OnGetPaymentURL_ReqResSvcOperationCompleted(object arg) {
            if ((this.GetPaymentURL_ReqResSvcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentURL_ReqResSvcCompleted(this, new GetPaymentURL_ReqResSvcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdRequestURL")]
    public partial class ashrait {
        
        private ashraitRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ashraitRequest request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdRequestURL")]
    public partial class ashraitRequest {
        
        private ashraitRequestDoDeal doDealField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ashraitRequestDoDeal doDeal {
            get {
                return this.doDealField;
            }
            set {
                this.doDealField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdRequestURL")]
    public partial class ashraitRequestDoDeal {
        
        private string totalField;
        
        private string currencyField;
        
        private string transactionTypeField;
        
        private string creditTypeField;
        
        private string transactionCodeField;
        
        private string terminalNumberField;
        
        private string firstPaymentField;
        
        private string periodicalPaymentField;
        
        private string numberOfPaymentsField;
        
        private string userField;
        
        private string midField;
        
        private string uniqueidField;
        
        private string mpiValidationField;
        
        private string descriptionField;
        
        private string emailField;
        
        private string userData1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creditType {
            get {
                return this.creditTypeField;
            }
            set {
                this.creditTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalNumber {
            get {
                return this.terminalNumberField;
            }
            set {
                this.terminalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstPayment {
            get {
                return this.firstPaymentField;
            }
            set {
                this.firstPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodicalPayment {
            get {
                return this.periodicalPaymentField;
            }
            set {
                this.periodicalPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numberOfPayments {
            get {
                return this.numberOfPaymentsField;
            }
            set {
                this.numberOfPaymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mid {
            get {
                return this.midField;
            }
            set {
                this.midField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uniqueid {
            get {
                return this.uniqueidField;
            }
            set {
                this.uniqueidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpiValidation {
            get {
                return this.mpiValidationField;
            }
            set {
                this.mpiValidationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userData1 {
            get {
                return this.userData1Field;
            }
            set {
                this.userData1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/ESB")]
    public partial class ESBServiceResponseMetadata {
        
        private ResponseStatus responseStatusField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string responseCodeOriginatorField;
        
        private string serviceInstanceIdField;
        
        private long instanceWFIDField;
        
        private string correlationIdField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeOriginator {
            get {
                return this.responseCodeOriginatorField;
            }
            set {
                this.responseCodeOriginatorField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInstanceId {
            get {
                return this.serviceInstanceIdField;
            }
            set {
                this.serviceInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public long InstanceWFID {
            get {
                return this.instanceWFIDField;
            }
            set {
                this.instanceWFIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/ESB")]
    public enum ResponseStatus {
        
        /// <remarks/>
        NotDefined,
        
        /// <remarks/>
        AsyncPending,
        
        /// <remarks/>
        DecisionPending,
        
        /// <remarks/>
        NotApplicable,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        NoDataFound,
        
        /// <remarks/>
        BusinessError,
        
        /// <remarks/>
        TechnicalError,
        
        /// <remarks/>
        Canceled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Process {
        
        private string processCodeField;
        
        private Id idField;
        
        /// <remarks/>
        public string ProcessCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        public Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Id {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class Filter {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fnx.co.il/Fnx.ESB.Infra.Schemas")]
    public partial class ESBServiceRequestMetadata {
        
        private Filter filterField;
        
        private Id idField;
        
        private Process processField;
        
        private string callingAppInstanceTrackingIdField;
        
        private string versionField;
        
        private string interfaceField;
        
        private string callerField;
        
        private System.DateTime activityTimeField;
        
        private bool activityTimeFieldSpecified;
        
        private string serviceInstanceIdField;
        
        private string workspaceField;
        
        private string correlationIdField;
        
        /// <remarks/>
        public Filter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Process Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        public string CallingAppInstanceTrackingId {
            get {
                return this.callingAppInstanceTrackingIdField;
            }
            set {
                this.callingAppInstanceTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Interface {
            get {
                return this.interfaceField;
            }
            set {
                this.interfaceField = value;
            }
        }
        
        /// <remarks/>
        public string Caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActivityTime {
            get {
                return this.activityTimeField;
            }
            set {
                this.activityTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivityTimeSpecified {
            get {
                return this.activityTimeFieldSpecified;
            }
            set {
                this.activityTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInstanceId {
            get {
                return this.serviceInstanceIdField;
            }
            set {
                this.serviceInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public string Workspace {
            get {
                return this.workspaceField;
            }
            set {
                this.workspaceField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdResponseURL")]
    public partial class ashrait1 {
        
        private ashraitResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ashraitResponse response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdResponseURL")]
    public partial class ashraitResponse {
        
        private string resultField;
        
        private string messageField;
        
        private ashraitResponseDoDeal doDealField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ashraitResponseDoDeal doDeal {
            get {
                return this.doDealField;
            }
            set {
                this.doDealField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://FNX.ESB.CGCreditCard.Schemas.CreditGurdResponseURL")]
    public partial class ashraitResponseDoDeal {
        
        private string tokenField;
        
        private string mpiHostedPageUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpiHostedPageUrl {
            get {
                return this.mpiHostedPageUrlField;
            }
            set {
                this.mpiHostedPageUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPaymentURL_ReqResSvcCompletedEventHandler(object sender, GetPaymentURL_ReqResSvcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentURL_ReqResSvcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentURL_ReqResSvcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ashrait1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ashrait1)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ESBServiceResponseMetadata ESBServiceResponseMetadata {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ESBServiceResponseMetadata)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591